# Generated by Django 3.1 on 2020-09-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200902_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
