# Generated by Django 3.1 on 2020-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200904_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_attachment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
