# Generated by Django 3.1 on 2020-09-04 11:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200904_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_attachment',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
