# Generated by Django 3.1 on 2020-09-11 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20200911_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='vote_score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvoters',
            field=models.ManyToManyField(related_name='comment_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoters',
            field=models.ManyToManyField(related_name='comment_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='downvoters_total',
            field=models.ManyToManyField(related_name='post_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='upvoters_total',
            field=models.ManyToManyField(related_name='post_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
