# Generated by Django 3.1 on 2020-09-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200911_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['upvotes']},
        ),
    ]
